
version: '3.8'

services:
  
  bijoux_customer:
    image: bijoux_customer_image
    container_name: BIJOUX_customer
    build:
      context: ./BIJOUX_FE/BIJOUX-customer
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./BIJOUX_FE/BIJOUX-customer:/var/www/html  # Bind mount mã nguồn Laravel vào container
    restart: unless-stopped

  bijoux_manager:
    image: bijoux_manager_image
    container_name: BIJOUX_manager
    build:
      context: ./BIJOUX_FE/BIJOUX-manager
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./BIJOUX_FE/BIJOUX-manager/src:/var/www/html  # Bind mount mã nguồn Laravel vào container
    restart: unless-stopped

  bijoux_be:
    image: bijoux_be_image
    build:
      context: ./BIJOUX_BE          # Thư mục chứa Dockerfile của Laravel
      dockerfile: Dockerfile
    container_name: BIJOUX_BE 
    restart: unless-stopped         # Khởi động lại container nếu container bị dừng
    environment:
      DB_CONNECTION: mysql          # Driver kết nối MySQL (PHP extension đã được cài đặt trong Dockerfile)
      DB_HOST: my_sql         # Tên container MySQL để kết nối
      DB_PORT: 3306                 # Cổng mặc định của MySQL (3306) trong container chứ không phải cổng của máy host (3308)
      DB_DATABASE: bijoux_clean_data 
      DB_USERNAME: root
      DB_PASSWORD: 
    tty: true
    volumes:
      - ./BIJOUX_BE/:/var/www/html  # Bind mount mã nguồn Laravel vào container
    working_dir: /var/www/html/     # Đặt thư mục làm việc
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - 8000:80                                             # Ánh xạ cổng 80 (cổng mặc định của NGINX trong container) với cổng 8000 trên máy host
    volumes:
      - ./BIJOUX_BE/:/var/www/html                          # Bind mount mã nguồn Laravel vào container
    # - ./nginx/conf.d:/etc/nginx/conf.d/ 
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf # Mount tệp cấu hình Nginx

    networks:
      - app-network

  mysql:
    image: mysql:8.2                                        # Sử dụng image MY SQL từ Docker Hub
    container_name: my_sql
    environment:
      # MYSQL_ROOT_PASSWORD: 123
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: bijoux_clean_data
    volumes:
      - ./mysql_data:/var/lib/mysql                         # Lưu trữ dữ liệu vào thư mục cục bộ (bind mount, đồng bộ hóa dữ liệu giữa container và máy host)
      - "/run/desktop/mnt/host/d/vscode/MY PROJECT/BIJOUX JEWELRY PROJECT/bijoux/bijoux materials/bijoux_clean_data.sql:/docker-entrypoint-initdb.d/bijoux_clean_data.sql" # Mount (import) tệp SQL vào thư mục khởi tạo của MySQL
    ports:
      - "3308:3306"                                         # Ánh xạ cổng 3306 (cổng mặc định của MySQL trong container) với cổng 3308 trên máy host
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin # Sử dụng hình ảnh phpMyAdmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: my_sql     # Tên container MySQL để kết nối
      PMA_USER: root 
      PMA_PASSWORD: "" 
    ports:
      - "8081:80"                # Ánh xạ cổng 80 (cổng mặc định của phpMyAdmin trong container) với cổng 8081 trên máy host
    depends_on:
      - mysql                    # Đảm bảo MySQL được khởi chạy trước
    networks:
      - app-network

networks:
  app-network:
    driver: bridge




#######################################################################################################################################
# services:
#   # Dịch vụ Laravel PHP
#   bijoux_be:
#     build:
#       context: ./nhap_laravel  # Thư mục chứa Dockerfile của Laravel
#     container_name: laravel_app
#     ports:
#       - "8000:80"  # Ánh xạ port 80 của container với port 8000 trên máy host
#     volumes:
#       - ./nhap_laravel:/var/www/html  # Chia sẻ mã nguồn Laravel với container
#     environment:
#       - DB_HOST=mysql
#       - DB_PORT=3307
#       - DB_DATABASE=bijoux_clear_data
#       - DB_USERNAME=root
#     depends_on:
#       - mysql  # Laravel phụ thuộc vào MySQL
#     networks:
#       - laravel_network

#   # Dịch vụ MySQL
#   mysql:
#     image: mysql:8.0
#     container_name: mysql_db
#     ports:
#       - "3307:3307"  # Ánh xạ port 3306 để truy cập MySQL từ máy host
#     environment:
#       MYSQL_ROOT_PASSWORD:   # Mật khẩu root cho MySQL
#       MYSQL_DATABASE: bijoux_clear_data   # Cơ sở dữ liệu mặc định
#       MYSQL_USER:              # Người dùng bổ sung
#       MYSQL_PASSWORD:  # Mật khẩu cho user
#     volumes:
#       - db_data:/var/lib/mysql  # Lưu trữ dữ liệu của MySQL trong volume
#     networks:
#       - laravel_network

#   # Dịch vụ phpMyAdmin
#   phpmyadmin:
#     image: phpmyadmin/phpmyadmin
#     container_name: phpmyadmin
#     ports:
#       - "8080:80"  # Truy cập phpMyAdmin thông qua cổng 8080 trên máy host
#     environment:
#       PMA_HOST: mysql  # Liên kết với container MySQL
#       MYSQL_ROOT_PASSWORD: secret
#     depends_on:
#       - mysql  # phpMyAdmin phụ thuộc vào MySQL
#     networks:
#       - laravel_network

# volumes:
#   db_data:  # Volume cho MySQL

# networks:
#   laravel_network:  # Mạng dùng chung cho tất cả các dịch vụ
